# Generated by Django 4.1 on 2022-09-12 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familia',
            old_name='fechadenacimiento',
            new_name='fecha',
        ),
    ]
